### ISSUE TITLE
Add a Sender that sends values with filtering

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/integration-tools#17]
We should add another instance of a WebserverSender configured to send some IASIOs that are not Alarms. This sender should have a filter to send only some of those IASIOs because only some of them would be of interest.

**Comment by acaproni** [comment]
The API of the core already allows to set filters, Do you really need to run another sender? Or, would that be enough to improve the actual filtering, if neded?

**Comment by sfehlandt** [comment]
I do not know. We need to try.
Regardless of how, this issue is to add the functionality to the docker-compose files

**Comment by sfehlandt** [comment]
Closed by 15b7d5e4c54707af2b5be97f021aaa83525dbde1
