### ISSUE TITLE
Upgrade kafka

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/integration-tools#2]
Dockers shall install the same version of kafka and zookeeper delivered by the core (and tested by jenkins).
The main reason is that we do not want to test one environment different from what goes in operations.

For the same reason, the configuration of kafka and zookepeer must be taken from the core.

We currently use the spotify kafka container for scala 2.11 and kafka 0.10.1.0.
Dockerhub offers something more close to our environment like [wurstmeister/kafka](https://hub.docker.com/r/wurstmeister/kafka/~/dockerfile/) for scala 2.12 and with kafka 1.0

**Comment by sfehlandt** [comment]
There is now a newer version of kafka 1.1.0, so we should use that one

**Comment by sfehlandt** [comment]
Closed by 63b5b5905b3d3dbe1f44973afd16fd1770e79699
