### ISSUE TITLE
Set logs folder to the folder pointed  by IAS_LOGS_FOLDER

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/integration-tools#20]
Logs are saved in a folder set in the `IAS_LOGS_FOLDER` environment path. This variable should be used instead of hardcoded paths.
If the environmkent variable is not set, the logs should be written in `$IAS_ROOT/logs`.

The rationale is that in operation the folder of the logs could be mounted in a dedicated server for several reasons.

**Comment by sfehlandt** [comment]
This is covered by the logic implemented and agreed in the last strategy of deployment mounting the IAS_ROOT.
