### ISSUE TITLE
Log rotation does not seem to work with docker containers

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/integration-tools#21]
Log rotation does not work with dockers: there are a lot of log files in the logs folder that exhaust the disk space. I just tested with a plain IAS core installation where the rotation works as expected, but this is what there is in the production server:

```
> ls  Supervisor-Supervisor-Antennas.2018-09-29*.log|wc
     64      64    3259
> du -hs
8.0G 
```

One possibility is that the `logback.xml` is not found/installed.

For testing there is a log producer in the test folder of the Utils module: `org.eso.ias.utils.test.ScalaLoggerTest`:

```
> iasRun -l s org.eso.ias.utils.test.ScalaLoggerTest
```

**Comment by sfehlandt** [comment]
It seems to work now, probably since we are mounting the IAS_ROOT.
Can you check @acaproni ?

**Comment by sfehlandt** [comment]
It works now on the server. Possibly due to the change that mounts the IAS_ROOT.
