### ISSUE TITLE
Change Webserver's sqlite databases

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/integration-tools#7]
Currenlty, the Webserver has 2 internal databases in sqlite format: tickets.sqlite and cdb.sqlite

We should change them to persistent Postgres databases in the docker-compose files.
At first we will have 2 Postgres databases: CDB and Tickets. Then CDB will be replaced by the real IAS CDB and Tickets may be merged to the IAS LTDB.

**Comment by acaproni** [comment]
Sebastian we should be consistent here and use the same RDBMS between the core and the web server.
The core is now using oracle xe that is a free version of of oracle. It has some limitations but it is enough for the needs of the IAS.

Oracle is the RDBMS used by ALMA and this is the reason I took this one even if I would have taken an open source one. If we want to use another RDBMS, I would have to double check with people here.

**Comment by sfehlandt** [comment]
Closed dut to above comment and issue [#45](https://github.com/IntegratedAlarmSystem-Group/ias-webserver/issues/45) of Webserver
